export const products = [
  {
    id: 1,
    image: "bo1.png",
    title: "set 2 bodysuit đùi Ht búp bê Animo M522004-19",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 167000,
    unit: "VNĐ",
  },
  {
    id: 2,
    image: "bo10.jpg",
    title: "full set hưu cao cổ (0-12M, vàng)",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 200000,
    unit: "VNĐ",
  },
  {
    id: 3,
    image: "bo2.jpg",
    title: "bộ bé gái lửng Cá sao biển Animo CL822046",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 107000,
    unit: "VNĐ",
  },
  {
    id: 4,
    image: "bo3.jpg",
    title: "giày tập đi Animo A2207_MN030",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 99000,
    unit: "VNĐ",
  },
  {
    id: 5,
    image: "bo4.jpg",
    title: "giày tập đi cao cấp Animo A2204_MN017",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 149000,
    unit: "VNĐ",
  },
  {
    id: 6,
    image: "bo5.jpg",
    title: "bodysuit sơ sinh dài vải Cotton, Animo I0122003",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 119000,
    unit: "VNĐ",
  },
  {
    id: 7,
    image: "bo6.jpg",
    title: "bộ bao tay chân sơ sinh thun BA423028",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 45000,
    unit: "VNĐ",
  },
  {
    id: 8,
    image: "bo7.png",
    title: "set 2 body tam giác Animo NB522013",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 131000,
    unit: "VNĐ",
  },
  {
    id: 9,
    image: "bo8.jpg",
    title: "nón lưỡi trai khăn voan bé trai Animo A2312_MN011",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 97000,
    unit: "VNĐ",
  },
  {
    id: 10,
    image: "bo9.jpg",
    title: "nón vành tròn khăn voan bé gái Animo A2312_MN017",
    size: ["XS", "M" , "XM"],
    description: "đây là đồ trẻ em",
    price: 96000,
    unit: "VNĐ",
  },
];
